#!/usr/bin/env bash
# vim: set ft=sh:ts=2:sw=2

## Check if the User has a Configuration File and use this
if [ -f ~/.vhm.cfg ];
then
  source ~/.vhm.cfg
else
  # Default Path of the Configuration File. You should use this location!
  source /usr/local/etc/vhm/vhm.cfg
fi

### VARIABLES AND CONSTANTS
action_create=-1
action_enable=-1
action_disable=-1
action_delete=-1
action_info=-1
action_status=-1
apache_restart=-1
server_port=$default_port

### FUNCTINS
disable () {
 if [ -f $sites_enabled/$1.conf ]
 then
   rm $sites_enabled/$1.conf
 fi
}

usage () {
  echo "Usage: vhm --domain example.dev --create --enable --apache-restart"
  echo
  echo "Parameter:"
  echo "cr  | -cr  | --create           create VirtualHost"
  echo "en  | -en  | --enable           enable VirtualHost"
  echo "dis | -dis | --disable          disable VirtualHost"
  echo "del | -del | --delete           delete VirtualHost"
  echo "ar  | -ar  | --apache-restart   Restart Apache"
  echo "-i  | --info              show VirtualHost File for given Domain"
  echo "-p  | --port              show VirtualHost File for given Domain"
  echo "-s  | --status            show VirtualHost (enabled, disabled, not created)"
  echo "-d  | --domain            Domain Name for the VirtualHost"
  echo "-t  | --template          Template Name to use for this Host"
  echo "-h  | --help              This little message"
  echo
  echo "Parameter can be combined. So --create and --enable in one command is possible"
  echo
  echo "You may not use --create and --delete in one command."
  echo "Same goes for --enable and --disable."
  echo "That would be ..."
  echo
}

### MAIN
if [ $# -eq 0 ]; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
  case $1 in
    -p | --port)
      shift
      server_port=$1
    ;;
    -h | --help)
      usage
      exit 0
      ;;
    -d | --domain)
      shift
      domain=$1
      ;;
    ar | -ar | --apache-restart)
      apache_restart=1
      ;;
    -t | --template)
      shift
      template=$1
      ;;
    cr | -cr | --create)
      action_create=1
     ;;
    en | -en | --enable)
      action_enable=1
      ;;
    dis | -dis | --disable)
      action_disable=1
      ;;
    del | -del | --delete)
      action_delete=1
      ;;
    -i | --info)
      action_info=1
      ;;
    -s | --status)
      action_status=1
      ;;
    *)
     ;;
  esac
  shift
done


if [ "$domain" == "" ]; then
  echo
  echo "Error: missing domain"
  echo
  usage
  exit 1
else
  if [ $action_status -eq 1 ];
  then
    if [ -f $sites_enabled/$domain.conf ];
    then
      echo "Status: enabled"
    else
      if [ -f $sites_available/$domain.conf ];
      then
        echo "Status: disabled"
      else
        echo "Status: not created"
      fi
    fi
  fi

  if [ $action_create -eq 1 ] && [ $action_delete -eq 1 ]; then
    usage
    exit 1
  elif [ $action_create -eq 1 ]; then
    vhost_template=$template_folder/$template_default
    sed "s@SERVER-ADMIN@$admin_email@g;s@SERVER-PATH-ROOT@$(pwd)@g;s@SERVER-NAME@$domain@g;s@SERVER-PATH-LOG@$server_path_log@g;s@SERVER-PORT@$server_port@g" $vhost_template > $sites_available/$domain.conf
  elif [ $action_delete -eq 1 ]; then
    disable $domain
    rm $sites_available/$domain.conf
  fi

  if [ $action_disable -eq 1 ] && [ $action_enable -eq 1 ]; then
    usage
    exit 1
  elif [ $action_enable -eq 1 ]; then
    ln -s $sites_available/$domain.conf $sites_enabled/$domain.conf
  elif [ $action_disable -eq 1 ]; then
    disable $domain
  fi

  if [ $action_info -eq 1 ];
  then
    if [ -f $sites_available/$domain.conf ];
    then
      cat $sites_available/$domain.conf
    else
      echo "Configuration not found"
    fi
  fi

  if [ $apache_restart -eq 1 ]; then
    echo "restarting Apache using sudo"
    sudo apachectl restart
  fi
fi
